//! Keeping `BUILTIN_NAMES` honest.
//!
//! The list is generated by scraping dispatch arms, which also picks up
//! match arms that are not builtins at all (theme names, option strings).
//! This calls every listed name and reports the ones the interpreter does
//! not recognise, so the index cannot claim a function that isn't there.

use qu_interp::{Interp, BUILTIN_NAMES};

#[test]
fn every_listed_builtin_is_a_real_builtin() {
    let mut bogus = Vec::new();
    for name in BUILTIN_NAMES {
        let mut it = Interp::new();
        // Called with no arguments on purpose: a real builtin complains
        // about ARGUMENTS (or succeeds), while a name that does not exist
        // says so. Either way nothing here depends on what it computes.
        let err = match it.run(&format!("__probe = {name}()")) {
            Ok(()) => continue,
            Err(e) => e.to_string(),
        };
        if err.contains("unknown function") || err.contains("is not defined") {
            bogus.push(*name);
        }
    }
    assert!(
        bogus.is_empty(),
        "{} entries in BUILTIN_NAMES are not builtins: {:?}",
        bogus.len(),
        bogus
    );
}

#[test]
fn the_index_is_sorted_and_has_no_duplicates() {
    // Sorted so `apropos` output is stable and a human can scan it.
    let mut sorted = BUILTIN_NAMES.to_vec();
    sorted.sort_unstable();
    sorted.dedup();
    assert_eq!(sorted.len(), BUILTIN_NAMES.len(), "duplicates in BUILTIN_NAMES");
    assert_eq!(sorted, BUILTIN_NAMES.to_vec(), "BUILTIN_NAMES is not sorted");
}

#[test]
fn the_index_covers_the_functions_people_actually_reach_for() {
    // A spot check that the scrape did not miss whole families.
    for name in [
        "plot", "fft", "mean", "curve_fit", "read_csv", "table", "linspace",
        "knn_model", "welch", "findpeaks", "savefig", "sort_by", "parse_json",
    ] {
        assert!(
            BUILTIN_NAMES.contains(&name),
            "{name} is missing from the builtin index"
        );
    }
}

// ------------------------------------------------------- did you mean

#[test]
fn a_partial_name_suggests_the_full_one() {
    // The reported case: reaching for `fit` when the answer was
    // `curve_fit`. A builtin CONTAINING what was typed is the strongest
    // signal, and the shortest such name comes first.
    let hits = qu_interp::similar_builtins("fit");
    assert!(hits.contains(&"curve_fit"), "got {hits:?}");
}

#[test]
fn a_transposition_suggests_the_right_spelling() {
    // Transpositions cost 2 in Levenshtein and are the most common typo,
    // so an edit budget that rejects them defeats the whole feature.
    for (typo, want) in [("lenght", "length"), ("plto", "plot"), ("meen", "mean"), ("revrse", "reverse")] {
        let hits = qu_interp::similar_builtins(typo);
        assert_eq!(hits.first(), Some(&want), "{typo} should suggest {want}, got {hits:?}");
    }
}

#[test]
fn nonsense_gets_no_suggestions_rather_than_a_wild_guess() {
    assert!(qu_interp::similar_builtins("zzzzzzzz").is_empty());
    assert!(qu_interp::similar_builtins("").is_empty());
}

#[test]
fn short_names_do_not_suggest_every_other_short_name() {
    // At an edit budget of 2, `sin` would offer `min`, `max` and `abs` --
    // noise, not help. Three-character names keep a budget of 1.
    let hits = qu_interp::similar_builtins("sin");
    assert!(!hits.contains(&"max"), "coincidental match in {hits:?}");
    assert!(!hits.contains(&"abs"), "coincidental match in {hits:?}");
}

#[test]
fn the_unknown_function_error_carries_the_suggestion() {
    let err = Interp::new().run("x = lenght([1,2,3])").unwrap_err().to_string();
    assert!(err.contains("did you mean"), "no suggestion in: {err}");
    assert!(err.contains("length"), "wrong suggestion in: {err}");
    // The old message listed categories that never contained the answer.
    assert!(!err.contains("M2 builtin set"), "stale category list: {err}");
}

#[test]
fn apropos_finds_a_family_by_word() {
    let mut it = Interp::new();
    it.run(r#"hits = apropos("filter")"#).unwrap();
    let Some(qu_interp::Value::List(hits)) = it.get("hits") else { panic!("not a list") };
    assert!(hits.len() >= 3, "expected several filter builtins, got {}", hits.len());
}

#[test]
fn builtins_lists_them_all() {
    let mut it = Interp::new();
    it.run("n = length(builtins())").unwrap();
    assert!(
        matches!(it.get("n"), Some(qu_interp::Value::Num(n)) if (*n - BUILTIN_NAMES.len() as f64).abs() < 1e-9)
    );
}

#[test]
fn help_confirms_a_real_name_and_corrects_a_wrong_one() {
    let mut it = Interp::new();
    it.run(r#"help("curve_fit")"#).unwrap();
    // `help()` now answers with the real signature and description from
    // `BUILTIN_DOCS` (generated from the stdlib book) rather than the old
    // generic "curve_fit is a Qu builtin." -- that line is only a
    // fallback now, for the small remainder the book doesn't document.
    assert!(it.out.contains("curve_fit(model, xdata, ydata, p0"), "{}", it.out);

    let mut it2 = Interp::new();
    it2.run(r#"help("fitt")"#).unwrap();
    assert!(it2.out.contains("did you mean"), "{}", it2.out);
}
